version: "3.4"

networks:
  default:
    driver: bridge
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_LISTEN_PORT: 5050
  #   ports:
  #     - "5050:5050"
  #   depends_on:
  #     - db

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    command: server /data --console-address :9001

  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
